[tool.poetry]
name = "open-deep-research"
version = "0.1.0"
description = ""
authors = ["xiaoye_hua <huag@kth.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
